name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Verify Secrets
      run: |
        echo "MONGO_URL is ${{ env.MONGO_URL }}"
        echo "DOCKER_USERNAME is ${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD is set"

    - name: Build backend image
      run: docker build --build-arg MONGO_URL=${{ secrets.MONGO_URL }} -t backend-node ./backend-node

    - name: Build frontend image
      run: docker build -t frontend ./frontend

    - name: Run tests on backend
      run: docker run --rm -e MONGO_URL=${{ secrets.MONGO_URL }} backend-node npm test