name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Copy .env file
      run: cp .env.example .env  # Certifique-se de que o arquivo .env.example existe e contém as variáveis necessárias

    - name: Verify MONGO_URL
      run: echo "MONGO_URL is ${{ env.MONGO_URL }}"  # Verifique se a URL do MongoDB está carregada corretamente

    - name: Build Docker images
      run: docker-compose build  # Construa as imagens Docker

    - name: Run tests
      run: docker-compose run backend npm test  # Execute os testes no contêiner backend