name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 3000:80

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: docker-compose up --build -d

    - name: Run tests
      run: docker-compose exec backend npm test

    - name: Save state example
      run: echo "myState=someValue" >> $GITHUB_STATE

    - name: Set output example
      run: echo "myOutput=someValue" >> $GITHUB_OUTPUT
