name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Atualizado para v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Atualizado para v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Verify Secrets
      run: |
        echo "MONGO_URL is ${{ env.MONGO_URL }}"
        echo "DOCKER_USERNAME is ${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD is set"

    - name: Build and push Docker images
      run: docker-compose up --build -d

    - name: Run tests
      run: docker-compose exec backend npm test